### ISSUE TITLE
Best practices to exclude folders from compilation?

### ISSUE THREAD

**Issue by ianfixes** [ianfixes/arduino_ci#29]
## Issue / Feature Request Summary
A configuration parameter to exclude folders from compilation. 

Consider a case where all libraries are in `./lib` so they can all be in a single git hub repo (using git submodules). `arduino_ci` walks the tree to find all the header files - irrespective of any compiler directives to use mock headers/classes instead, the libraries get pulled in too (which may break compilation).

**Comment by dolfandringa** [comment]
I would really love to have this feature. Issue #69 could have been easily fixed with this feature (jsut add .bundle to the ignore path) but I am combining arduino_ci with https://github.com/ladislas/Bare-Arduino-Project which both fill part of my use-case, but neither fill both. Right now the Bare-Arduino-Project makefiles are adding files to my repos, that cause arduino_ci tests to fail because arduino_ci is including those files in the build process. They are temporary files that I don't need, so manually removing them before running tests fixes the problem. But I wish I could just ignore the respective folders instead.

**Comment by ianfixes** [comment]
`arduino_ci` is meant to test standalone libraries, not bundled libraries (i.e., it expects to run from the root of an [Arduino library](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification)). This is an interesting use case though.  I assume that you could simply change the working directory to the library you wanted to test, and then run the script.  Do you have code up that shows the failure?

**Comment by dolfandringa** [comment]
@ianfixes I currently made it work from the root directory, when adding the linked PR. A demo version can be found onhttps://github.com/dolfandringa/Bare-Arduino-Project

**Comment by ianfixes** [comment]
What does your bare arduino project do if there are multiple libraries in the `lib` directory?
